# Generated by Django 5.2.17 on 2026-09-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chips_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
