# Generated by Django 5.2.17 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_chips_limit_staffuser_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbankaccount',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
