# Generated by Django 5.2.17 on 2026-09-17 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_playerbankaccount_paystack_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='floormanager',
            name='staff_user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'FLOOR_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('CASHIER', 'Cashier'), ('ACCOUNTANT', 'Accountant'), ('OWNER', 'Owner'), ('FLOOR_MANAGER', 'Floor Manager')], max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_staff_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
