# Hand-written (not autogenerated) — Masseuse/Dealer/Service staff roles
# added 2026-09-23, per the Owner's request ("add dealer and masseuse to
# the list of staff an owner can add"). See PLAN.md's dated entry.
#
# Two independent changes bundled here:
#   1. Three new StaffUser.Role login-role choices (MASSEUSE/DEALER/SERVICE)
#      — no schema change beyond the choices list itself.
#   2. ServiceStaff renamed to Masseuse — the named tip-recipient roster,
#      relabeled the same day Transaction.TipCategory's DEALER/SERVICE
#      values were renamed SERVICE_STAFF/MASSEUSE (see gaming's own
#      migration for that Transaction-side change). RenameModel preserves
#      every existing row and every FK pointing at it (gaming.Transaction.
#      masseuse, renamed in that same gaming migration, which depends on
#      this one).
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_floormanager_staff_user_alter_staffuser_role_and_more'),
        # Forces this to run AFTER every existing gaming migration — several
        # of them (0007 onward) add/reference a field pointing at
        # 'accounts.servicestaff'. Without this, the migration graph's
        # topological sort is free to apply this RenameModel before those,
        # leaving a lazy reference to a model name that no longer exists.
        ('gaming', '0016_gamedaysummary_chip_discrepancy_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('CASHIER', 'Cashier'), ('ACCOUNTANT', 'Accountant'), ('OWNER', 'Owner'),
                    ('FLOOR_MANAGER', 'Floor Manager'), ('MASSEUSE', 'Masseuse'),
                    ('DEALER', 'Dealer'), ('SERVICE', 'Service'),
                ],
                max_length=20,
            ),
        ),
        migrations.RenameModel(old_name='ServiceStaff', new_name='Masseuse'),
        migrations.AlterField(
            model_name='masseuse',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='masseuses_added',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
