# Generated by Django 5.2.17 on 2026-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staffmember_and_revert_login_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chips_limit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
