# Generated by Django 5.2.17 on 2026-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='account_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountcode',
            name='account_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
