# Generated by Django 5.2.17 on 2026-10-02 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountcode_account_name_accountcode_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcode',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Must be exactly 10 digits.')]),
        ),
    ]
