# Generated by Django 5.2.17 on 2026-09-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('MAIN', 'Main account'), ('GAMING', 'Gaming account')], max_length=10)),
                ('paystack_integration_id', models.CharField(max_length=100)),
                ('integration_name', models.CharField(max_length=150)),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gaming_account', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='DedicatedVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paystack_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvas', to='payments.paystackaccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paystackaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'MAIN')), fields=('account_type',), name='only_one_main_account'),
        ),
    ]
