# Generated by Django 5.2.17 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paystackaccount',
            old_name='integration_name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='paystackaccount',
            name='paystack_integration_id',
        ),
        migrations.RemoveField(
            model_name='paystackaccount',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='paystackaccount',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='paystackaccount',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='dedicatedvirtualaccount',
            name='paystack_dva_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paystackaccount',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
