# Generated by Django 5.2.17 on 2026-09-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_days_closed', to=settings.AUTH_USER_MODEL)),
                ('closed_by_floor_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_days_closed', to='accounts.floormanager')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_days_opened', to=settings.AUTH_USER_MODEL)),
                ('opened_by_floor_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_days_opened', to='accounts.floormanager')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('OTHER', 'Other')], max_length=10)),
                ('rate_to_naira', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_set', to=settings.AUTH_USER_MODEL)),
                ('set_by_floor_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_set', to='accounts.floormanager')),
                ('game_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_rates', to='gaming.gameday')),
            ],
        ),
        migrations.CreateModel(
            name='GameDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_players', models.PositiveIntegerField()),
                ('chips_out_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chips_in_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rake_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tips_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chips_outstanding', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=14)),
                ('game_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='gaming.gameday')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHIPS_OUT', 'Chips out'), ('CHIPS_IN', 'Chips in'), ('CHIPS_OFFSITE_OUT', 'Chips taken off-site'), ('CHIPS_OFFSITE_RETURN', 'Off-site chips returned'), ('PAYMENT_CASH', 'Cash payment'), ('PAYMENT_TRANSFER', 'Transfer payment'), ('PAYMENT_POS', 'POS payment'), ('PAYMENT_DEAL', 'Deal'), ('PAYOUT', 'Payout to player'), ('WRITE_OFF', 'Write-off / credit'), ('RAKE', 'Rake'), ('TIP', 'Tip')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('channel', models.CharField(choices=[('CASHIER', 'Cashier'), ('TRANSFER_DVA', 'Transfer (DVA)'), ('CASH', 'Cash'), ('POS', 'POS'), ('CHIPS', 'Chips'), ('DEAL', 'Deal'), ('WRITE_OFF', 'Write-off')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='POSTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_approved', to=settings.AUTH_USER_MODEL)),
                ('floor_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_confirmed', to='accounts.floormanager')),
                ('game_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gaming.gameday')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.player')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_recorded', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game_day', 'player'], name='gaming_tran_game_da_8cf186_idx'), models.Index(fields=['player', 'created_at'], name='gaming_tran_player__827c1f_idx')],
            },
        ),
    ]
