# Generated by Django 5.2.17 on 2026-09-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedaysummary',
            old_name='chips_outstanding',
            new_name='chips_variance',
        ),
        migrations.AlterField(
            model_name='conversionrate',
            name='set_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fx_rates_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='opened_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OWNER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_days_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CHIPS_OUT', 'Chips out'), ('CHIPS_IN', 'Chips in'), ('PAYMENT_CASH', 'Cash payment'), ('PAYMENT_TRANSFER', 'Transfer payment'), ('PAYMENT_POS', 'POS payment'), ('PAYMENT_DEAL', 'Deal'), ('PAYOUT', 'Payout to player'), ('WRITE_OFF', 'Write-off / credit'), ('RAKE', 'Rake'), ('TIP', 'Tip')], max_length=25),
        ),
    ]
