# Generated by Django 5.2.17 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_rename_chips_outstanding_gamedaysummary_chips_variance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSFER_FAILED', 'Transfer failed')], default='POSTED', max_length=20),
        ),
    ]
