# Generated by Django 5.2.17 on 2026-09-14 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_playerbankaccount_paystack_recipient_code'),
        ('gaming', '0003_alter_transaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDayPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players_seated', to=settings.AUTH_USER_MODEL)),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seated_players', to='gaming.gameday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_day_seats', to='accounts.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_day', 'player'), name='unique_player_per_game_day_seat')],
            },
        ),
    ]
