# Generated by Django 5.2.17 on 2026-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0004_gamedayplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedayplayer',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
