# Generated by Django 5.2.17 on 2026-09-17 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_playerbankaccount_paystack_recipient_code'),
        ('gaming', '0005_gamedayplayer_left_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedayplayer',
            name='seat_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='gamedayplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True), ('seat_number__isnull', False)), fields=('game_day', 'seat_number'), name='unique_active_seat_per_game_day'),
        ),
    ]
