# Generated by Django 5.2.17 on 2026-09-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_floormanager_staff_user_alter_staffuser_role_and_more'),
        ('gaming', '0006_gamedayplayer_seat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tips_received', to='accounts.servicestaff'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tip_category',
            field=models.CharField(blank=True, choices=[('DEALER', 'Dealer'), ('SERVICE', 'Service')], max_length=10, null=True),
        ),
    ]
