# Generated by Django 5.2.17 on 2026-09-20 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0007_transaction_service_staff_transaction_tip_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gaming.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CHIPS_OUT', 'Chips out'), ('CHIPS_IN', 'Chips in'), ('PAYMENT_CASH', 'Cash payment'), ('PAYMENT_TRANSFER', 'Transfer payment'), ('PAYMENT_POS', 'POS payment'), ('PAYMENT_DEAL', 'Deal'), ('PAYOUT', 'Payout to player'), ('WRITE_OFF', 'Write-off / credit'), ('RAKE', 'Rake'), ('TIP', 'Tip'), ('DEAL_TRANSFER_OUT', 'Deal transfer (out)'), ('DEAL_TRANSFER_IN', 'Deal transfer (in)')], max_length=25),
        ),
    ]
