# Generated by Django 5.2.17 on 2026-09-20 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_floormanager_staff_user_alter_staffuser_role_and_more'),
        ('gaming', '0008_transaction_linked_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CHIPS_OUT', 'Chips out'), ('CHIPS_IN', 'Chips in'), ('PAYMENT_CASH', 'Cash payment'), ('PAYMENT_TRANSFER', 'Transfer payment'), ('PAYMENT_POS', 'POS payment'), ('PAYMENT_DEAL', 'Deal'), ('PAYOUT', 'Payout to player'), ('WRITE_OFF', 'Write-off / credit'), ('RAKE', 'Rake'), ('TIP', 'Tip'), ('DEAL_TRANSFER_OUT', 'Deal transfer (out)'), ('DEAL_TRANSFER_IN', 'Deal transfer (in)'), ('PROFIT_SPLIT_STAKE', 'Profit split — house stake')], max_length=25),
        ),
        migrations.CreateModel(
            name='ProfitSplitArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_stake_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cap_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reset_cadence', models.CharField(choices=[('ONE_OFF', 'One-off'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONE_OFF', max_length=10)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_resets', models.PositiveIntegerField(blank=True, null=True)),
                ('max_cumulative_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payout_basis', models.CharField(choices=[('BEFORE_BUYIN', 'Before buy-in'), ('AFTER_BUYIN', 'After buy-in')], default='AFTER_BUYIN', max_length=15)),
                ('payout_split_method', models.CharField(choices=[('STAKE_RATIO', 'Ratio: according to stake'), ('CUSTOM_RATIO', 'Ratio: house percentage'), ('FIXED', 'Fixed amount')], default='STAKE_RATIO', max_length=15)),
                ('custom_ratio_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fixed_offset', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_splits_created', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_split_arrangements', to='accounts.player')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit_split_arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gaming.profitsplitarrangement'),
        ),
    ]
