# Generated by Django 5.2.17 on 2026-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0011_seed_games_and_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
