# Generated by Django 5.2.17 on 2026-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0015_remove_transaction_table_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedaysummary',
            name='chip_discrepancy_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
