# Generated by Django 5.2.17 on 2026-09-23 07:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0018_transaction_masseuse_points_at_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_approval_open_game_day', models.BooleanField(default=True)),
                ('require_approval_close_game_day', models.BooleanField(default=True)),
                ('require_approval_return_chips', models.BooleanField(default=True)),
                ('require_approval_add_tip', models.BooleanField(default=True)),
                ('require_approval_add_rake', models.BooleanField(default=True)),
                ('payout_auto_approve_threshold', models.DecimalField(decimal_places=2, default=Decimal('500000'), max_digits=14)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='big_blind',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='max_chips_issuable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='rake_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='small_blind',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
