# Generated by Django 5.2.17 on 2026-09-23 09:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0019_club_settings_and_table_editable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsettings',
            name='payout_auto_approve_threshold',
            field=models.DecimalField(decimal_places=0, default=Decimal('500000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='buy_in_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='chips_in_total',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='chips_out_total',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='chips_variance',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='game_balance',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='rake_total',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='tips_total',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='gamedaysummary',
            name='total_payments',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='profitsplitarrangement',
            name='cap_amount',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='profitsplitarrangement',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='profitsplitarrangement',
            name='fixed_offset',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='profitsplitarrangement',
            name='max_cumulative_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='big_blind',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='default_buy_in',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='table',
            name='max_chips_issuable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='small_blind',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
