# Generated by Django 5.2.17 on 2026-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0020_money_fields_whole_naira'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='require_approval_issue_chips',
            field=models.BooleanField(default=True),
        ),
    ]
