# Generated by Django 5.2.17 on 2026-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0021_clubsettings_require_approval_issue_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='owner_dashboard_game_day_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
