# Generated by Django 5.2.17 on 2026-09-24 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountcode'),
        ('gaming', '0022_clubsettings_owner_dashboard_game_day_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['game_day', 'created_at'], name='gaming_tran_game_da_9f670a_idx'),
        ),
    ]
