# Generated by Django 5.2.17 on 2026-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0023_transaction_gaming_tran_game_da_9f670a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
