# Generated by Django 5.2.17 on 2026-09-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0024_transaction_requested_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='away_max_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='cashier_can_initiate_payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='min_player_time_minutes',
            field=models.PositiveIntegerField(default=240),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='observe_min_player_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='track_away_from_table',
            field=models.BooleanField(default=False),
        ),
    ]
