# Generated by Django 5.2.17 on 2026-09-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0026_backfill_profit_split_stake_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_buy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_applications', to='gaming.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CHIPS_OUT', 'Chips out'), ('CHIPS_IN', 'Chips in'), ('PAYMENT_CASH', 'Cash payment'), ('PAYMENT_TRANSFER', 'Transfer payment'), ('PAYMENT_POS', 'POS payment'), ('PAYMENT_DEAL', 'Deal'), ('PAYOUT', 'Payout to player'), ('WRITE_OFF', 'Write-off / credit'), ('RAKE', 'Rake'), ('TIP', 'Tip'), ('DEAL_TRANSFER_OUT', 'Deal transfer (out)'), ('DEAL_TRANSFER_IN', 'Deal transfer (in)'), ('PROFIT_SPLIT_STAKE', 'Profit split — house stake'), ('PLAYER_BALANCE_IN', 'Player balance'), ('PLAYER_BALANCE_OUT', 'Player balance (carried forward)')], max_length=25),
        ),
    ]
