# Generated by Django 5.2.17 on 2026-10-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0027_transaction_source_buy_in_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='auto_issue_buy_in_on_seating',
            field=models.BooleanField(default=False),
        ),
    ]
