# Generated by Django 5.2.17 on 2026-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0028_clubsettings_auto_issue_buy_in_on_seating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitsplitarrangement',
            name='reset_cadence',
            field=models.CharField(choices=[('ONE_OFF', 'One-off'), ('PER_GAME', 'Per game')], default='ONE_OFF', max_length=10),
        ),
    ]
