# Generated by Django 5.2.17 on 2026-10-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountcode_account_name_accountcode_account_number'),
        ('gaming', '0030_backfill_reset_cadence_per_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('CHIPS_OUT', 'Issued chips'), ('CHIPS_IN', 'Returned chips'), ('PAYMENT', 'Recorded a payment'), ('RAKE', 'Recorded rake'), ('TIP', 'Recorded a tip'), ('WRITE_OFF', 'Wrote off a balance'), ('DEAL_TRANSFER', "Transferred a player's balance"), ('VOID', 'Voided an entry'), ('SEAT_PLAYER', 'Seated a player'), ('LEAVE_TABLE', 'Marked a player as left the table'), ('MOVE_SEAT', 'Moved a seat'), ('OPEN_GAME_DAY', 'Opened a game-day'), ('CLOSE_GAME_DAY', 'Closed a game-day'), ('PAYOUT_REQUESTED', 'Requested a payout'), ('PAYOUT_APPROVED', 'Approved a payout'), ('PAYOUT_REJECTED', 'Rejected a payout'), ('DEAL_CREATED', 'Set up a deal'), ('DEAL_ENDED', 'Ended a deal'), ('CREDIT_LIMIT_CHANGED', "Changed a player's credit limit"), ('SETTINGS_CHANGED', 'Changed club settings'), ('TABLE_CHANGED', 'Changed a table'), ('STAFF_CREATED', 'Created a staff account'), ('PASSWORD_RESET', 'Reset a password'), ('PIN_RESET', 'Reset a PIN'), ('ACCOUNT_CODES_ADDED', 'Added account codes'), ('PLAYER_CREATED', 'Registered a player'), ('LOGIN', 'Logged in')], max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('game_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='gaming.gameday')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.player')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='gaming.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
