# Generated by Django 5.2.17 on 2026-10-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0031_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CHIPS_OUT', 'Chips out'), ('CHIPS_IN', 'Chips in'), ('PAYMENT_CASH', 'Cash payment'), ('PAYMENT_TRANSFER', 'Transfer payment'), ('PAYMENT_POS', 'POS payment'), ('PAYMENT_DEAL', 'Deal'), ('PAYOUT', 'Payout to player'), ('WRITE_OFF', 'Write-off / credit'), ('RAKE', 'Rake'), ('TIP', 'Tip'), ('DEAL_TRANSFER_OUT', 'Deal transfer (out)'), ('DEAL_TRANSFER_IN', 'Deal transfer (in)'), ('PROFIT_SPLIT_STAKE', 'Profit split — house stake'), ('PROFIT_SPLIT_RETURN', 'Profit split — house return'), ('PLAYER_BALANCE_IN', 'Player balance'), ('PLAYER_BALANCE_OUT', 'Player balance (carried forward)')], max_length=25),
        ),
    ]
